### ISSUE TITLE
Releases for Dropwizard 1.3.16, 1.3.17, 2.0?

### ISSUE THREAD

**Issue by cricket007** [dropwizard/dropwizard-kafka#64]
Noticed releases are not added for 1.3.16,1.3.17, and 2.0 versions.

**Comment by cricket007** [comment]
Link 

- #50 
- #56 
- #58

**Comment by mzamani1** [comment]
I generally don’t plan to release for every patch version upgrade, as a project should pin to the version of Dropwizard and dependency manage every other dependency to that version.

Regarding 2.0.0 support, I’m planning to set aside some time to get that done after the holidays. Happy to accept/review PRs before then, otherwise I’ll take care of it in the next few weeks.

**Comment by cricket007** [comment]
> as a project should pin to the version of Dropwizard and dependency manage every other dependency to that version.

Doh, that makes sense. 😅

> I’m planning to set aside some time to get that done after the holidays

No rush, just wanted to see if it was on the radar. Happy to help where needed.

**Comment by mzamani1** [comment]
`1.3.17` is now supported. My current plan is to set aside some time this weekend to get `2.0.0` support hammered out!

**Comment by mzamani1** [comment]
@cricket007 Released version `1.5.0`, which is built with Dropwizard `2.0.0`

**Comment by cricket007** [comment]
Awesome. Thanks for taking the time to do it. Looks like fairly simple changes.

I noticed the tag in the README isn't being updated when you prep the releases, though
